package com.example.webservice.hxInvoice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.11
 * 2022-03-29T12:10:55.326+08:00
 * Generated source version: 2.5.11
 * 
 */
@WebServiceClient(name = "EInvWebServiceImplService", 
                  wsdlLocation = "https://www.ahdzfp.com/services/eInvWS?wsdl",
                  targetNamespace = "http://ws.aisino.com") 
public class EInvWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.aisino.com", "EInvWebServiceImplService");
    public final static QName EInvWebServiceImplPort = new QName("http://ws.aisino.com", "EInvWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://www.ahdzfp.com/services/eInvWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EInvWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://www.ahdzfp.com/services/eInvWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EInvWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EInvWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EInvWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EInvWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EInvWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EInvWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IEInvWebService
     */
    @WebEndpoint(name = "EInvWebServiceImplPort")
    public IEInvWebService getEInvWebServiceImplPort() {
        return super.getPort(EInvWebServiceImplPort, IEInvWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEInvWebService
     */
    @WebEndpoint(name = "EInvWebServiceImplPort")
    public IEInvWebService getEInvWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EInvWebServiceImplPort, IEInvWebService.class, features);
    }

}
