package com.example.webservice.hxInvoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.11
 * 2022-03-29T12:10:55.301+08:00
 * Generated source version: 2.5.11
 * 
 */
@WebService(targetNamespace = "http://ws.aisino.com", name = "IEInvWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IEInvWebService {

    @WebMethod
    @RequestWrapper(localName = "eiInterface", targetNamespace = "http://ws.aisino.com", className = "com.example.webservice.hxInvoice.EiInterface")
    @ResponseWrapper(localName = "eiInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.example.webservice.hxInvoice.EiInterfaceResponse")
    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    public String eiInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        String in0
    );
}
