package com.example.webservice.rhInvoice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.11
 * 2022-03-29T16:34:35.480+08:00
 * Generated source version: 2.5.11
 * 
 */
@WebServiceClient(name = "WKWebService", 
                  wsdlLocation = "http://111.202.226.69:9026/zxkp/services/WKWebService?wsdl",
                  targetNamespace = "http://impl.service.tax.inspur") 
public class WKWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.tax.inspur", "WKWebService");
    public final static QName WKWebServiceSOAP11PortHttp = new QName("http://impl.service.tax.inspur", "WKWebServiceSOAP11port_http");
    public final static QName WKWebServiceSOAP12PortHttp = new QName("http://impl.service.tax.inspur", "WKWebServiceSOAP12port_http");
    public final static QName WKWebServiceHttpport = new QName("http://impl.service.tax.inspur", "WKWebServiceHttpport");
    static {
        URL url = null;
        try {
            url = new URL("http://111.202.226.69:9026/zxkp/services/WKWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WKWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://111.202.226.69:9026/zxkp/services/WKWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WKWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WKWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WKWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WKWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WKWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WKWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WKWebServicePortType
     */
    @WebEndpoint(name = "WKWebServiceSOAP11port_http")
    public WKWebServicePortType getWKWebServiceSOAP11PortHttp() {
        return super.getPort(WKWebServiceSOAP11PortHttp, WKWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WKWebServicePortType
     */
    @WebEndpoint(name = "WKWebServiceSOAP11port_http")
    public WKWebServicePortType getWKWebServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(WKWebServiceSOAP11PortHttp, WKWebServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns WKWebServicePortType
     */
    @WebEndpoint(name = "WKWebServiceSOAP12port_http")
    public WKWebServicePortType getWKWebServiceSOAP12PortHttp() {
        return super.getPort(WKWebServiceSOAP12PortHttp, WKWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WKWebServicePortType
     */
    @WebEndpoint(name = "WKWebServiceSOAP12port_http")
    public WKWebServicePortType getWKWebServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(WKWebServiceSOAP12PortHttp, WKWebServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns WKWebServicePortType
     */
    @WebEndpoint(name = "WKWebServiceHttpport")
    public WKWebServicePortType getWKWebServiceHttpport() {
        return super.getPort(WKWebServiceHttpport, WKWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WKWebServicePortType
     */
    @WebEndpoint(name = "WKWebServiceHttpport")
    public WKWebServicePortType getWKWebServiceHttpport(WebServiceFeature... features) {
        return super.getPort(WKWebServiceHttpport, WKWebServicePortType.class, features);
    }

}
