package com.example.webservice.rhInvoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.11
 * 2022-03-29T16:34:35.457+08:00
 * Generated source version: 2.5.11
 * 
 */
@WebService(targetNamespace = "http://impl.service.tax.inspur", name = "WKWebServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface WKWebServicePortType {

    @WebMethod(action = "urn:doService")
    @Action(input = "urn:doService", output = "urn:doServiceResponse")
    @RequestWrapper(localName = "doService", targetNamespace = "http://impl.service.tax.inspur", className = "DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://impl.service.tax.inspur", className = "DoServiceResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.service.tax.inspur")
    public String doService(
        @WebParam(name = "xml", targetNamespace = "http://impl.service.tax.inspur")
        String xml
    );
}
